name: Python DevSecOps CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pytest

      - name: Run Tests
        run: |
          pytest

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls -la

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

      - name: Build Docker Image
        run: |
          docker build -t devsecops-app .